services:
  redis1:
    container_name: redis1
    image: redis:6.0.7
    restart: always
    volumes:
      - redis:/data/db
    ports:
      - 6379:6379
  redis2:
    container_name: redis2
    image: redis:6.0.7
    restart: always
    volumes:
      - redis:/data/db
    ports:
      - 6380:6379
  redis3:
    container_name: redis3
    image: redis:6.0.7
    restart: always
    volumes:
      - redis:/data/db
    ports:
      - 6381:6379
  #redis_insight:
  #  container_name: redis_insight
  #  image: redislabs/redisinsight:latest
  #  restart: always
  #  ports:
  #    - 8001:8001
  #  volumes:
  #    - redis_insight:/data/db

networks:
  redisCluster:
    name: redisCluster

volumes:
  redis:
  #redis_insight: