services:
  redis1:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./dbSaves/redis1:/data/db/redis.conf
    command: redis-server /data/db/redis.conf
  redis2:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - ./dbSaves/redis2:/data/db/redis.conf
    command: redis-server /data/db/redis.conf
  redis3:
    image: redis:latest
    ports:
      - "6381:6381"
    volumes:
      - ./dbSaves/redis3:/data/db/redis.conf
    command: redis-server /data/db/redis.conf
  #redis_insight:
  #  container_name: redis_insight
  #  image: redislabs/redisinsight:latest
  #  restart: always
  #  ports:
  #    - 8001:8001
  #  volumes:
  #    - redis_insight:/data/db
  redis-cluster:
    image: redis:latest
    hostname: server
    depends_on:
      - redis1
      - redis2
      - redis3

networks:
  redisCluster:
    name: redisCluster

volumes:
  redis:
  #redis_insight: